name: Deploy React App to AWS S3 static hosting via AWS CDK

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install App dependencies
        working-directory: ./src
        run: npm ci

      - name: Build App
        working-directory: ./src
        run: npm run build

      - name: Install CDK dependencies
        working-directory: aws
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: CDK Synth
        working-directory: aws
        run: npx cdk synth

      - name: CDK Deploy
        working-directory: aws
        run: npx cdk deploy
